name: example
description: Romanize package example.
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.0
  web: ^1.1.1
  romanize:
    path: ../

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.0
  lints: ^5.0.0

dependency_overrides:
  kuromoji:
    git:
      url: https://github.com/bdlukaa/kuromoji
      ref: web-support

jaspr:
  mode: client
