name: romanize
description: A lightweight Dart package for converting Korean, Japanese, Chinese, Cyrillic, and Arabic text to Romanized form with auto-detection support.
version: 0.0.1
repository: https://github.com/themelodyai/romanize
issue_tracker: https://github.com/themelodyai/romanize/issues

environment:
  sdk: ^3.8.0

dependencies:
  # Romanizers

  ## Japanese
  kuromoji: ^1.0.4
  kana_kit: ^2.1.1

  ## Chinese
  pinyin: ^3.3.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  lints: ^5.0.0
  test: ^1.24.0
