name: romanize
description: A lightweight Dart package for converting Arabic, Chinese, Cyrillic, Hebrew, Japanese and Korean text to Romanized form with auto-detection support.
version: 0.0.3
repository: https://github.com/themelodyai/romanize
issue_tracker: https://github.com/themelodyai/romanize/issues

environment:
  sdk: ^3.8.0

funding:
  - https://github.com/sponsors/bdlukaa

dependencies:
  # Romanizers

  ## Japanese
  kuromoji: ^1.0.5
  kana_kit: ^2.1.1

  ## Chinese
  pinyin: ^3.3.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  lints: ^5.0.0
  test: ^1.24.0
