name: romanize
description: Convert text to Romanized form.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  # Romanizers
  korean_romanization_converter: ^0.0.1
  kana_kit: ^2.1.1
  pinyin: ^3.3.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  lints: ^5.0.0
  test: ^1.24.0
